name: make-daily-revo-archive

on:
  schedule:
  # ĉiumatene, devas esti post rekreo de la eldono poer make-daily-release (30min devus esti sekura...)
  # se make-daily-release fiaskas, tiam Revo-Zip aldoniĝos al la malnova eldono, tio eble ne estas problemo
  # dum iom da tempo (ĉ. 1 horo) ne ekzistas Revo-ZIP, ĉar la malnova eldono foriĝis kaj tiu ĉi estas ankoraŭ ne preta
  # do se vi bezonas ĝin prenu ĝin ne lunde matene antaŭ 9:30 UTC, sed pli poste...
  
  # * estas speciala signo, do nepre uzu citilojn
  - cron:  '45 8 * * *'
  #- cron:  '34 19 * * 2'

# https://github.com/actions/create-release
# https://help.github.com/en/actions/reference/development-tools-for-github-actions
# https://github.com/actions/github-script

jobs:

  revo-aktualigo:
    #needs: release
    runs-on: ubuntu-latest

    steps:

    - name: "Hodiaŭ..."
      run: |
        Tagoj=(Dimanĉo Lundo Mardo Merkredo Ĵaudo Vendredo Sabato)
        echo "::set-env name=TAGO::${Tagoj[ $(date +'%w') ]}"

    - name: Eltrovu la URL de la hodiaŭa eldono
      uses: actions/github-script@0.4.0
      id: retrieve_release
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        debug: true
        script: |
            const release = await github.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,            
                tag: 'v${{ env.TAGO }}'
            })
            const upload_url = release.data.upload_url            
            console.log('UploadURL is: '+upload_url)
            console.log('::set-output name=upload_url::'+upload_url)

    - uses: actions/github-script@0.4.0
      name: Eltrovu la pozicion de marko 'nokta-formiko'
      id: trovu_noktan_formikon
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        debug: true
        script: |
          const ref = await github.git.getRef({...context.repo, ref: 'tags/nokta-formiko'})
          const sha = ref.data.object.sha
          console.log('nokta-formiko estas ĉe: '+sha)
          console.log('::set-output name=sha_nf::'+sha)

    - uses: actions/github-script@0.4.0
      name: Eltrovu la nunan pozicion (kapo)
      id: trovu_kapon
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        debug: true
        script: |
          const ref = await github.git.getRef({...context.repo, ref: 'heads/master'})
          const sha = ref.data.object.sha
          console.log('heads/master estas ĉe: '+sha)
          console.log('::set-output name=sha_hm::'+sha)

    # https://github.community/t5/GitHub-Actions/Use-docker-images-from-GitHub-Package-Registry/td-p/30407    
    # https://github.com/actions/starter-workflows/blob/master/ci/docker-push.yml    
    - name: Saluto al docker.pkg.github.com kaj preni voko-formiko
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        docker pull "docker.pkg.github.com/revuloj/voko-formiko/voko-formiko:latest"

    # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
    - name: Kreu dosierujojn por konservi la rezultojn ...
      run: |
        mkdir .tgz
        mkdir .log

    - name: Kreu la tutan vortaron ĉe nokta-formiko kaj HEAD kaj arĥivu la diferencon
      if: steps.trovu_noktan_formikon.outputs.sha_nf != steps.trovu_kapon.outputs.sha_hm
      run: docker run -u1001
        -e GIT_REPO_REVO=https://github.com/revuloj/revo-fonto.git
        -e FTP_SERVER=cyberwebserver-21.de
        -e FTP_USER=${{ secrets.FTP_USER }}
        -e FTP_PASSWD=${{ secrets.FTP_PASSWD }}
        -e CGI_SERVER=reta-vortaro.de
        -e CGI_USER=${{ secrets.CGI_USER }}
        -e CGI_PASSWD=${{ secrets.CGI_PASSWD }}
        -v $GITHUB_WORKSPACE/.tgz:/home/formiko/tgz
        -v $GITHUB_WORKSPACE/.log:/home/formiko/log
        docker.pkg.github.com/revuloj/voko-formiko/voko-formiko:latest formiko
        -Dsha1=${{ steps.trovu_noktan_formikon.outputs.sha_nf }} 
        -Dsha2=${{ steps.trovu_kapon.outputs.sha_hm }}
        srv-servo-diferenco-github

    - name: Rigardu la rezulton
      run: |
        #tar -czf revo.tgz $GITHUB_WORKSPACE/revo
        ls -l .tgz/ .log/

    - name: Retrovu la rezultintan ZIP-dosierujon
      if: steps.trovu_noktan_formikon.outputs.sha_nf != steps.trovu_kapon.outputs.sha_hm
      id: revo_zip
      run: |
        ls -l $GITHUB_WORKSPACE/.tgz
        echo "::set-output name=revohtml::$(basename -- .tgz/revohtml_20*)"

    - name: Alpendigu revo-zip al la hodiaŭa eldono
      if: steps.trovu_noktan_formikon.outputs.sha_nf != steps.trovu_kapon.outputs.sha_hm
      id: upload-zip 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.retrieve_release.outputs.upload_url }} 
        asset_path: .tgz/${{ steps.revo_zip.outputs.revohtml }}
        asset_name: ${{ steps.revo_zip.outputs.revohtml }}
        asset_content_type: application/zip        

    - name: Konservu rezultintajn arĥivojn
      uses: actions/upload-artifact@v1
      with:
        name: tgz
        path: .tgz

    - name: Konservu protokolojn
      uses: actions/upload-artifact@v1
      with:
        name: log
        path: .log

    - uses: actions/github-script@0.4.0
      if: steps.trovu_noktan_formikon.outputs.sha_nf != steps.trovu_kapon.outputs.sha_hm
      name: Movu antaŭen la formikon
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        debug: true
        script: |
          var result = {};
          try {
            result = await github.git.updateRef({  
              owner: context.repo.owner,
              repo: context.repo.repo,            
              sha: '${{ steps.trovu_kapon.outputs.sha_hm }}',
              ref: 'tags/nokta-formiko',
              force: true })
          } catch(error) {
            console.log("ERROR:");
          }
          console.log("RESULT...")
          console.log(result)        

# about download: https://help.github.com/en/github/administering-a-repository/linking-to-releases
# verŝajne ni devos eltrovi per Github-API, almenaŭ ni devos scii la daton por scii la nomon de ZIP-dosiero!
# https://github.com/revuloj/revo-fonto/releases/latest/download/<asset-name.zip>

# https://developer.github.com/v3/repos/releases/#get-the-latest-release
# GET /repos/:owner/:repo/releases/latest
# t.e. GET https://api.github.com/repos/revuloj/revo-fonto/releases/latest
#
# data.assets.name = xxxx.zip
# data.assets.browser_download_url
#
# ĉu ni bezonas saluti nur por legi? Eble ne,...
# alternative ni povus aldoni dosier-liston al la eldono por eviti neceson de API-Token
