name: submeto-purigo

on:
  schedule:
  # ĉiunokte
  
  # ĉiun unuan de monato purigu...
  # la tempo estas laŭ UTC
  # * estas speciala signo, do nepre uzu citilojn
  - cron:  '5 22 1 * *'
  #- cron:  '51 13 * * *'


jobs:

  submeto-purigo:
    runs-on: ubuntu-latest

    steps:
      - name: "Forigas malnovajn submetojn el la datumbazo"
        run: |
          curl -u ${{ secrets.CGI_USER }}:${{ secrets.CGI_PASSWD }} https://reta-vortaro.de/cgi-bin/admin/submeto.pl?forigo=1
